version: '3'

services:
  puppeteer-api:
    build:
      context: .
      dockerfile: dockerfile
    init: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./app:/app
    working_dir: /app
    # entrypoint: /app/entrypoint.sh
    ports:
      - "80:3001"
    networks:
      - puppeteer

networks:
  puppeteer:
    driver: bridge
